version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: always
  api:
    build: ./api
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
    restart: always